### ISSUE TITLE
Two config files are published

### ISSUE THREAD

**Issue by prikkprikkprikk** [mitydigital/statamic-iconamic#1]
When I run

`php artisan vendor:publish --tag=iconamic-config`

… the iconamic.php config file is published both in config/statamic/iconamic.php and in config/iconamic.php.

**Comment by martyf** [comment]
Thanks for that - you can safely remove the `config/iconamic.php` file - that one is not used.

I'll get a fix for this released.

**Comment by martyf** [comment]
An update has been released to correct this for new installs.

**Comment by prikkprikkprikk** [comment]
Sorry, it seems this creates another error:

> Statamic \ Exceptions \ FieldtypeNotFoundException
> Fieldtype [iconamic] not found

**Comment by martyf** [comment]
Rollback to v1.0.0 and manually remove the rouge config file - will get a new release up in the next day or two after tweaking the component init.

**Comment by martyf** [comment]
v1.0.2 has been released.

This permanently moves the config file to `config/iconamic.php`. 

I'd suggest removing `config/iconamic.php` if it still exists, and then do the update - the update script will try to move the file for you. If it can't, you'll need to manually check everything is correct.

I've also done a clean install with this version and all works, so fingers crossed you're smooth sailing.

**Comment by prikkprikkprikk** [comment]
Excellent! It managed to move the file for me. All OK!

**Comment by martyf** [comment]
Woohoo good stuff :D
