### ISSUE TITLE
Pass attributes to SVG tag?

### ISSUE THREAD

**Issue by klickreflex** [mitydigital/statamic-iconamic#2]
Is there a way to pass attributes to the svg tag that is generated by `{{ iconamic }}`?
I need to add some classes to my icons and it would work best if they were applied directly to the svg tag itself.

**Comment by martyf** [comment]
Not currently, but leave it with me... stay tuned.

**Comment by martyf** [comment]
Just released 1.1.1 which adds support for attributes.

You can now pass attributes with the Iconamic tag:
```antlers 
{{ iconamic icon="my-icon" class="w-4 h-4" }}
```

Iconamic will then inject these attributes to the svg tag:
```html
<svg ... class="w-4 h-4">...</svg>
```

If your icons already have a `class` attribute, you can use `class` to append, or `classReplace` to overwrite your existing attribute.

This works for any attribute too, not just `class`.

Full details are at:
https://docs.mity.com.au/iconamic/adding-attributes

**Comment by klickreflex** [comment]
Wow, this is fantastic, thank you so much for the quick improvement @martyf  🙏

Now I can change my workaround using a native svg tag with the svg chosen by iconamic 😍

**Comment by martyf** [comment]
You're welcome - sometimes we don't think of things ourselves, so thanks for the suggestion :)
